export const GITHUB_TOKEN_BROKER_FEATURE_GATE_POLICY = Symbol(
  "GITHUB_TOKEN_BROKER_FEATURE_GATE_POLICY",
);
export const GITHUB_TOKEN_BROKER_SETTINGS = Symbol("GITHUB_TOKEN_BROKER_SETTINGS");
export const GITHUB_APP_JWT_SIGNER = Symbol("GITHUB_APP_JWT_SIGNER");
export const GITHUB_INSTALLATION_TOKEN_ISSUER = Symbol(
  "GITHUB_INSTALLATION_TOKEN_ISSUER",
);
export const GITHUB_TOKEN_TARGET_AUTHORIZATION = Symbol(
  "GITHUB_TOKEN_TARGET_AUTHORIZATION",
);
export const GITHUB_TOKEN_BROKER_AUDIT_LOG = Symbol("GITHUB_TOKEN_BROKER_AUDIT_LOG");
export const GITHUB_TOKEN_BROKER_ABUSE_CONTROL = Symbol(
  "GITHUB_TOKEN_BROKER_ABUSE_CONTROL",
);
