export const EXTERNAL_ACTION_CONTENT_REPOSITORY = Symbol(
  "EXTERNAL_ACTION_CONTENT_REPOSITORY",
);
export const EXTERNAL_ACTION_CONTENT_ENCRYPTION = Symbol(
  "EXTERNAL_ACTION_CONTENT_ENCRYPTION",
);
