export const GITHUB_SETUP_REPOSITORY = Symbol("GITHUB_SETUP_REPOSITORY");
export const GITHUB_SETUP_FEATURE_GATE_POLICY = Symbol(
  "GITHUB_SETUP_FEATURE_GATE_POLICY",
);
export const GITHUB_SETUP_ABUSE_CONTROL_POLICY = Symbol(
  "GITHUB_SETUP_ABUSE_CONTROL_POLICY",
);
export const GITHUB_SETUP_AUDIT_LOG = Symbol("GITHUB_SETUP_AUDIT_LOG");
export const GITHUB_SETUP_ENTROPY = Symbol("GITHUB_SETUP_ENTROPY");
export const GITHUB_APP_SETUP_SETTINGS = Symbol("GITHUB_APP_SETUP_SETTINGS");
export const PKCE_SECRET_STORE = Symbol("PKCE_SECRET_STORE");
export const GITHUB_USER_TOKEN_EXCHANGE = Symbol("GITHUB_USER_TOKEN_EXCHANGE");
export const GITHUB_CLAIM_AUTHORITY_VERIFIER = Symbol("GITHUB_CLAIM_AUTHORITY_VERIFIER");
