export const WORKSPACE_IDENTITY_REPOSITORY = Symbol("WORKSPACE_IDENTITY_REPOSITORY");
export const WORKSPACE_IDENTITY_FEATURE_GATE_POLICY = Symbol(
  "WORKSPACE_IDENTITY_FEATURE_GATE_POLICY",
);
export const WORKSPACE_IDENTITY_ABUSE_CONTROL_POLICY = Symbol(
  "WORKSPACE_IDENTITY_ABUSE_CONTROL_POLICY",
);
export const WORKSPACE_IDENTITY_AUDIT_LOG = Symbol("WORKSPACE_IDENTITY_AUDIT_LOG");
export const WORKSPACE_IDENTITY_ENTROPY = Symbol("WORKSPACE_IDENTITY_ENTROPY");
export const DESKTOP_TOKEN_SECRET_STORE = Symbol("DESKTOP_TOKEN_SECRET_STORE");
