export const AGENT_GITHUB_ACTIONS_FEATURE_GATE_POLICY = Symbol(
  "AGENT_GITHUB_ACTIONS_FEATURE_GATE_POLICY",
);
export const AGENT_GITHUB_ACTIONS_SETTINGS = Symbol("AGENT_GITHUB_ACTIONS_SETTINGS");
export const AGENT_GITHUB_ACTIONS_AUDIT_LOG = Symbol("AGENT_GITHUB_ACTIONS_AUDIT_LOG");
export const GITHUB_ACTION_REPOSITORY = Symbol("GITHUB_ACTION_REPOSITORY");
export const GITHUB_ACTION_CONTENT_STORE = Symbol("GITHUB_ACTION_CONTENT_STORE");
export const GITHUB_ACTION_OUTBOX = Symbol("GITHUB_ACTION_OUTBOX");
export const GITHUB_ACTION_TARGET_POLICY_EVALUATOR = Symbol(
  "GITHUB_ACTION_TARGET_POLICY_EVALUATOR",
);
export const GITHUB_ACTION_TOKEN_BROKER = Symbol("GITHUB_ACTION_TOKEN_BROKER");
export const GITHUB_ACTION_DISPATCHER = Symbol("GITHUB_ACTION_DISPATCHER");
export const GITHUB_ACTION_ID_GENERATOR = Symbol("GITHUB_ACTION_ID_GENERATOR");
