export const PRISMA_DATABASE_CLIENT = Symbol("PRISMA_DATABASE_CLIENT");
export const TRANSACTION_RUNNER = Symbol("TRANSACTION_RUNNER");
export const DATABASE_READINESS_PROBE = Symbol("DATABASE_READINESS_PROBE");
