import { join } from "node:path";
import {
  RunEventProviderKind,
  projectScopedControllerToolNames,
  type ControlledAgentProviderEnforcementCapabilities,
} from "@vioxen/subscription-runtime/worker-core";
import {
  codexProviderEgressConfigToml,
  codexProviderEgressEnv,
} from "@vioxen/subscription-runtime/provider-codex";

export type CodexControlledAgentProfileInput = {
  readonly stateDir: string;
  readonly mcpServerName?: string;
  readonly mcpCommand?: string;
  readonly mcpArgs?: readonly string[];
  readonly mcpCwd?: string;
  readonly rawShellMode?: "disabled-by-provider" | "sandboxed-deny-rules-only";
};

export type CodexControlledAgentProfile = {
  readonly providerKind: RunEventProviderKind.Codex;
  readonly codexHome: string;
  readonly configToml: string;
  readonly rulesText: string;
  readonly enabledTools: readonly string[];
  readonly appServerNativeToolSurface: "disabled" | "default";
  readonly enforcement: ControlledAgentProviderEnforcementCapabilities;
};

export function buildCodexControlledAgentProfile(
  input: CodexControlledAgentProfileInput,
): CodexControlledAgentProfile {
  const mcpServerName = input.mcpServerName ?? "subscription_runtime_project_control";
  const enabledTools = projectScopedControllerToolNames();
  const mcpCommand = input.mcpCommand ?? "subscription-runtime-codex-goal-mcp";
  const mcpArgs = input.mcpArgs ?? [];
  const codexHome = join(input.stateDir, "codex-home");
  const rawShellMode = input.rawShellMode ?? "disabled-by-provider";
  return {
    providerKind: RunEventProviderKind.Codex,
    codexHome,
    enabledTools,
    appServerNativeToolSurface: rawShellMode === "disabled-by-provider"
      ? "disabled"
      : "default",
    configToml: codexConfigToml({
      mcpServerName,
      mcpCommand,
      mcpArgs,
      enabledTools,
      ...(input.mcpCwd === undefined ? {} : { mcpCwd: input.mcpCwd }),
    }),
    rulesText: codexControllerRulesText(),
    enforcement: {
      providerKind: RunEventProviderKind.Codex,
      canRestrictToolSurface: true,
      canDisableRawShell: rawShellMode === "disabled-by-provider",
      canEnforceFilesystemSandbox: true,
      canIsolateHome: true,
      canIsolateTemp: true,
      canRestrictNetwork: true,
    },
  };
}

function codexConfigToml(input: {
  readonly mcpServerName: string;
  readonly mcpCommand: string;
  readonly mcpArgs: readonly string[];
  readonly mcpCwd?: string;
  readonly enabledTools: readonly string[];
}): string {
  const lines = [
    "# Generated by subscription-runtime controlled-agent. Do not add raw host tools.",
    'cli_auth_credentials_store = "file"',
    'sandbox_mode = "read-only"',
    'approval_policy = "never"',
    'web_search = "disabled"',
    "disable_response_storage = true",
    'model_verbosity = "low"',
    "",
    "[features]",
    "apps = false",
    "hooks = false",
    "memories = false",
    "multi_agent = false",
    "shell_snapshot = false",
    "skill_mcp_dependency_install = false",
    "",
    "[history]",
    'persistence = "none"',
    "",
    "[otel]",
    'exporter = "none"',
    'metrics_exporter = "none"',
    'trace_exporter = "none"',
    "log_user_prompt = false",
    "",
    `[mcp_servers.${quoteTomlKey(input.mcpServerName)}]`,
    `command = ${tomlString(input.mcpCommand)}`,
    `args = ${tomlStringArray(input.mcpArgs)}`,
    `enabled_tools = ${tomlStringArray(input.enabledTools)}`,
    'default_tools_approval_mode = "approve"',
    ...(input.mcpCwd ? [`cwd = ${tomlString(input.mcpCwd)}`] : []),
    "",
    "[shell_environment_policy]",
    'inherit = "none"',
    'include_only = ["PATH", "HOME", "CI", "CODEX_HOME"]',
    "",
    "[permissions.controlled_project_controller.filesystem]",
    '":minimal" = "read"',
    "",
    "[permissions.controlled_project_controller.network]",
    "enabled = false",
    "",
    codexProviderEgressConfigToml(),
  ];
  return `${lines.join("\n")}\n`;
}

function codexControllerRulesText(): string {
  return [
    "# Generated by subscription-runtime controlled-agent.",
    "# These rules are a defense-in-depth layer. Provider tool-surface enforcement is still required.",
    forbiddenRule(["git"], "Use project integration broker tools instead of raw git."),
    forbiddenRule(["tmux"], "Use project-control broker tools instead of raw tmux."),
    forbiddenRule(["ssh"], "Remote access is outside project-scoped control."),
    forbiddenRule(["scp"], "Remote file copy is outside project-scoped control."),
    forbiddenRule(["rsync"], "Remote file sync is outside project-scoped control."),
    forbiddenRule(["docker"], "Docker/socket access is outside project-scoped control."),
    forbiddenRule(["docker-compose"], "Docker/socket access is outside project-scoped control."),
    forbiddenRule(["podman"], "Container socket access is outside project-scoped control."),
    forbiddenRule(["sudo"], "Privilege escalation is outside project-scoped control."),
    forbiddenRule(["su"], "Privilege escalation is outside project-scoped control."),
    forbiddenRule(["bash", "-lc"], "Raw shell scripts are outside broker-only controller scope."),
    forbiddenRule(["bash", "-c"], "Raw shell scripts are outside broker-only controller scope."),
    forbiddenRule(["zsh", "-lc"], "Raw shell scripts are outside broker-only controller scope."),
    forbiddenRule(["zsh", "-c"], "Raw shell scripts are outside broker-only controller scope."),
    forbiddenRule(["sh", "-lc"], "Raw shell scripts are outside broker-only controller scope."),
    forbiddenRule(["sh", "-c"], "Raw shell scripts are outside broker-only controller scope."),
    "",
  ].join("\n");
}

function forbiddenRule(pattern: readonly string[], justification: string): string {
  return [
    "prefix_rule(",
    `    pattern = ${starlarkStringArray(pattern)},`,
    '    decision = "forbidden",',
    `    justification = ${tomlString(justification)},`,
    ")",
  ].join("\n");
}

function quoteTomlKey(value: string): string {
  return /^[A-Za-z0-9_-]+$/.test(value) ? value : JSON.stringify(value);
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function tomlStringArray(values: readonly string[]): string {
  return `[${values.map(tomlString).join(", ")}]`;
}

function starlarkStringArray(values: readonly string[]): string {
  return `[${values.map(tomlString).join(", ")}]`;
}

export const codexControlledAgentProviderEgressEnv = codexProviderEgressEnv;
